import express from 'express';
import auth from '../modules/auth';
import * as adminUsers from '../modules/admin/users';
import * as adminOptions from '../modules/admin/options';
import * as catalog from '../modules/catalog';
import * as media from '../modules/media';

const router = express.Router();
const { authMiddleware } = auth;
const requireAdmin = auth.requireRole('Administrador');

router.get('/users', authMiddleware, requireAdmin, adminUsers.listUsers);
router.patch('/users/:id/role', authMiddleware, requireAdmin, adminUsers.updateUserRole);
router.get('/options/:category', authMiddleware, requireAdmin, adminOptions.listOptions);
router.post('/options', authMiddleware, requireAdmin, adminOptions.createOption);
router.patch('/options/:category/order', authMiddleware, requireAdmin, adminOptions.reorderOptions);
router.patch('/options/:id', authMiddleware, requireAdmin, adminOptions.updateOption);
router.delete('/options/:id', authMiddleware, requireAdmin, adminOptions.deleteOption);
router.post('/media/covers', authMiddleware, requireAdmin, media.importCover);
router.delete('/media/covers/:assetId', authMiddleware, requireAdmin, media.deletePendingCover);
router.get('/works/form-options', authMiddleware, requireAdmin, adminOptions.getWorkFormOptions);
router.get('/editions/form-options', authMiddleware, requireAdmin, adminOptions.getEditionFormOptions);
router.get('/works', authMiddleware, requireAdmin, catalog.listWorks);
router.post('/works', authMiddleware, requireAdmin, catalog.createWork);
router.get('/works/slug/:slug', authMiddleware, requireAdmin, catalog.getWorkBySlug);
router.post('/works/:workId/editions', authMiddleware, requireAdmin, catalog.createEdition);
router.get('/works/:workId/editions', authMiddleware, requireAdmin, catalog.listEditionsByWork);
router.post('/editions/:editionId/volumes', authMiddleware, requireAdmin, catalog.createVolume);
router.get('/editions/:editionId/volumes', authMiddleware, requireAdmin, catalog.listVolumesByEdition);
router.patch('/works/:id/visibility', authMiddleware, requireAdmin, catalog.updateWorkVisibility);
router.get('/works/:id', authMiddleware, requireAdmin, catalog.getWorkById);
router.patch('/works/:id', authMiddleware, requireAdmin, catalog.updateWork);
router.delete('/works/:id', authMiddleware, requireAdmin, catalog.deleteWork);
router.get('/editions/:id', authMiddleware, requireAdmin, catalog.getEditionById);
router.patch('/editions/:id', authMiddleware, requireAdmin, catalog.updateEdition);
router.delete('/editions/:id', authMiddleware, requireAdmin, catalog.deleteEdition);
router.patch('/editions/:id/visibility', authMiddleware, requireAdmin, catalog.updateEditionVisibility);
router.get('/volumes/:id', authMiddleware, requireAdmin, catalog.getVolumeById);
router.patch('/volumes/:id', authMiddleware, requireAdmin, catalog.updateVolume);
router.delete('/volumes/:id', authMiddleware, requireAdmin, catalog.deleteVolume);

export = router;
